export const ANIMATION_FPS = 30;
export const ANIMATION_SECONDS = 5.5;
export const ANIMATION_DURATION_IN_FRAMES = ANIMATION_SECONDS * ANIMATION_FPS; // 165
export const COMPOSITION_WIDTH = 1920;
export const COMPOSITION_HEIGHT = 1080;
