export const ANIMATION_FPS = 30
export const ANIMATION_FRAME_TIME = 1000 / ANIMATION_FPS
export const ANIMATION_FRAME_TIME_SECONDS = ANIMATION_FRAME_TIME / 1000
export const ANIMATION_SECONDS = 5.5
export const ANIMATION_SPEEDUP = 1
export const GIF_ANIMATION_FRAME_TIME_DELAY = ANIMATION_FRAME_TIME_SECONDS * 3
